select * from customers

ALTER TABLE customers
ALTER COLUMN purchased_amount TYPE NUMERIC
USING purchased_amount::NUMERIC;

ALTER TABLE customers
ALTER COLUMN review_rating TYPE NUMERIC
USING review_rating::NUMERIC;

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchased_amount) as revenue
from customers  
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchased_amount 
from customers
where discount_applied = 'Yes' and purchased_amount >= (select AVG(purchased_amount) from customers)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased , ROUND(AVG(review_rating),2) as "Average Product Rating"
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Campare the average Purchase Amount between Standaard and Express Shipping.
select shipping_type, 
round(AVG(purchased_amount),2)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscibed customers spend more? Campare averag spend and total revenue
--between subcribers and non-subcribers.
select subscription_status,count(customer_id) as total_customers,
ROUND(AVG(purchased_amount),2) as avg_spend,
ROUND(SUM(purchased_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the hightest percentage of purchases with discounts applied?
select item_purchased,round(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers intoNew ,Returning,and Loyal based on their total 
--number of previous purchases,and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases::int = 1 THEN 'New'
	WHEN previous_purchases::int BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customers
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased product within each categories .
with item_counts as(
select item_purchased , category,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customers
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases::int > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,SUM(purchased_amount) as total_revenue
from customers
group by age_group
order by total_revenue;
